class WMProj_SonicBlastFullyCharged_HRG_SonicGun_Precious extends KFProj_SonicBlastFullyCharged_HRG_SonicGun
	hidedropdown;

defaultproperties
{
	Damage=14
	Name="Default__WMProj_SonicBlastFullyCharged_HRG_SonicGun_Precious"
}
