class WMProj_Bullet_Pistol_ChiappaRhinoShrapnel_Precious extends KFProj_Bullet_Pistol_ChiappaRhinoShrapnel;

defaultproperties
{
	Damage=100
	Name="Default__WMProj_Bullet_Pistol_ChiappaRhinoShrapnel_Precious"
}
