class WMProj_Bullet_Pistol_ChiappaRhino_Precious extends KFProj_Bullet_Pistol_ChiappaRhino
	hidedropdown;

defaultproperties
{
	ShrapnelClass=class'ZedternalReborn.WMProj_Bullet_Pistol_ChiappaRhinoShrapnel_Precious'
}
