class WMProj_SonicBlastUncharged_HRG_SonicGun_Precious extends KFProj_SonicBlastUncharged_HRG_SonicGun
	hidedropdown;

defaultproperties
{
	Damage=14
	Name="Default__WMProj_SonicBlastUncharged_HRG_SonicGun_Precious"
}
