class WMProj_Bullet_Pistol_ChiappaRhinoShrapnel_Precious extends KFProj_Bullet_Pistol_ChiappaRhinoShrapnel
	hidedropdown;

defaultproperties
{
	Damage=108
	Name="Default__WMProj_Bullet_Pistol_ChiappaRhinoShrapnel_Precious"
}
